name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Run tests
      run: xcodebuild test -project OnTrack.xcodeproj -scheme OnTrack -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0'
